### ISSUE TITLE
Hi from Berlin

### ISSUE THREAD

**Issue by VolkanSah** [ultrocharge/Real-Estate#3]
### Deutsch:

Sehr geehrte Entwickler,
ich möchte mich für Ihre interessante App bedanken. Das Konzept finde ich vielversprechend.
Da ich mich gerne tiefer mit Ihrer Anwendung auseinandersetzen möchte, hätte ich zwei Fragen:

-  Dokumentation: Könnten Sie bitte eine Dokumentation zur Verfügung stellen, die die Funktionsweise und die Verwendung Ihrer App detailliert beschreibt?
-  Lizenz: Unter welcher Lizenz wird Ihre App veröffentlicht? Diese Information ist für mich wichtig, um die Nutzungsrechte zu verstehen.

Vielen Dank im Voraus für Ihre Rückmeldung.
Mit freundlichen Grüßen aus Berlin

### Englisch:

Dear Developers,
Thank you for creating this interesting app. I find the concept promising.
As I'm eager to explore your application further, I have two questions:

- Documentation: Could you please provide documentation that details the functionality and usage of your app?
-  License: Under which license is your app released? This information is important for me to understand the usage rights.

Thank you in advance for your response.
Best regards from Berlin

**Comment by ultrocharge** [comment]
Thank you for your message.

The platform is a comprehensive solution for renting, buying, or selling
houses.

I only built the UI for this app.

so here, there are no doc or licenses.

sorry.

**Comment by VolkanSah** [comment]
Ok. Thanks for your quick answear. Nice UI. Well done. We will read us.
